<<<<<<< HEAD
DROP TABLE GGHJ_KAKAO CASCADE CONSTRAINTS;

/*카카오 유저 ---------------------------------------- */
CREATE TABLE GGHJ_KAKAO
(
    KAKAO_ID          NUMBER,--PK
    NAME          VARCHAR2(255) NOT NULL,
    PROFILE_PIC       VARCHAR2(255),
    PROVIDER       VARCHAR2(20),
    PROVIDER_ID     VARCHAR2(20) UNIQUE NOT NULL,
    CREATE_AT       DATE,
    UPDATE_AT       DATE,
    KAKAO_BIRTH      DATE,
    CONSTRAINT PK_KAKAO_USER PRIMARY KEY (KAKAO_ID)
);

CREATE SEQUENCE seq_uni START WITH 100;

SELECT * FROM GGHJ_KAKAO gk ;

DELETE FROM GGHJ_UNI WHERE UNI_ID BETWEEN 1 AND 10;

SELECT * FROM GGHJ_UNI;

DELETE FROM GGHJ_UNI;

SELECT * FROM GGHJ_KAKAO;


=======
DROP TABLE GGHJ_KAKAO CASCADE CONSTRAINTS;

/*카카오 유저 ---------------------------------------- */
CREATE TABLE GGHJ_KAKAO
(
    KAKAO_ID          NUMBER,--PK
    NAME          VARCHAR2(255) NOT NULL,
    PROFILE_PIC       VARCHAR2(255),
    PROVIDER       VARCHAR2(20),
    PROVIDER_ID     VARCHAR2(20) UNIQUE NOT NULL,
    CREATE_AT       DATE,
    UPDATE_AT       DATE,
    KAKAO_BIRTH      DATE,
    CONSTRAINT PK_KAKAO_USER PRIMARY KEY (KAKAO_ID)
);

CREATE SEQUENCE seq_uni START WITH 100;

SELECT * FROM GGHJ_KAKAO gk ;

DELETE FROM GGHJ_UNI WHERE UNI_ID BETWEEN 1 AND 10;

SELECT * FROM GGHJ_UNI;

DELETE FROM GGHJ_UNI;

SELECT * FROM GGHJ_KAKAO;


>>>>>>> ba7783b6573a0df4537eea9c4fe0af6ba8e183d7
D